/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const COMMON_DICT: typeof import('./utils/pinyinDict').COMMON_DICT
  const EffectScope: typeof import('vue').EffectScope
  const VIP_MAP: typeof import('./utils/pinyinDict').VIP_MAP
  const buildFolderMap: typeof import('./utils/bookmarksApi').buildFolderMap
  const calculateCoords: typeof import('./utils/positioning').calculateCoords
  const checkFit: typeof import('./utils/positioning').checkFit
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const debounce: typeof import('./utils/debounce').debounce
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const deleteImage: typeof import('./utils/db').deleteImage
  const downloadFile: typeof import('./utils/export').downloadFile
  const effectScope: typeof import('vue').effectScope
  const extractFolders: typeof import('./utils/bookmarksApi').extractFolders
  const flattenBookmarks: typeof import('./utils/bookmarksApi').flattenBookmarks
  const getAllImageIds: typeof import('./utils/db').getAllImageIds
  const getAllKeys: typeof import('./utils/db').getAllKeys
  const getAvailableSpace: typeof import('./utils/positioning').getAvailableSpace
  const getBookmarkTree: typeof import('./utils/bookmarksApi').getBookmarkTree
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getFirstLetter: typeof import('./utils/pinyin').getFirstLetter
  const getFolderPathFromMap: typeof import('./utils/bookmarksApi').getFolderPathFromMap
  const getImageKeys: typeof import('./utils/db').getImageKeys
  const getImageUrl: typeof import('./utils/db').getImageUrl
  const getPinyinFirstLetters: typeof import('./utils/pinyin').getPinyinFirstLetters
  const getWordCount: typeof import('./utils/wordCount').getWordCount
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isExtensionEnvironment: typeof import('./utils/bookmarksApi').isExtensionEnvironment
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const processImageWithWorker: typeof import('./utils/imageProcessor').processImageWithWorker
  const processMarkdownForExport: typeof import('./utils/export').processMarkdownForExport
  const provide: typeof import('vue').provide
  const provideContextMenu: typeof import('./composables/useContextMenu').provideContextMenu
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const removeImage: typeof import('./utils/db').removeImage
  const resolveComponent: typeof import('vue').resolveComponent
  const saveImage: typeof import('./utils/db').saveImage
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const stripMarkdown: typeof import('./utils/export').stripMarkdown
  const throttle: typeof import('./utils/throttle').throttle
  const throttleRaf: typeof import('./utils/throttle').throttleRaf
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAsyncWordCount: typeof import('./composables/useAsyncWordCount').useAsyncWordCount
  const useAttrs: typeof import('vue').useAttrs
  const useCalendarData: typeof import('./composables/useCalendarData').useCalendarData
  const useContextMenu: typeof import('./composables/useContextMenu').useContextMenu
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDraggableCard: typeof import('./composables/useDraggableCard').useDraggableCard
  const useId: typeof import('vue').useId
  const useImageGC: typeof import('./composables/useImageGC').useImageGC
  const useImageUpload: typeof import('./composables/useImageUpload').useImageUpload
  const useModel: typeof import('vue').useModel
  const useNotes: typeof import('./composables/useNotes').useNotes
  const useSettings: typeof import('./composables/useSettings').useSettings
  const useShortcutDrag: typeof import('./composables/useShortcutDrag').useShortcutDrag
  const useSimpleDrag: typeof import('./composables/useSimpleDrag').useSimpleDrag
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTodoDrag: typeof import('./composables/useTodoDrag').useTodoDrag
  const useTodos: typeof import('./composables/useTodos').useTodos
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { DayMetadata } from './composables/useCalendarData'
  import('./composables/useCalendarData')
  // @ts-ignore
  export type { OptionItem } from './composables/useContextMenu'
  import('./composables/useContextMenu')
  // @ts-ignore
  export type { Note, SortMode } from './composables/useNotes'
  import('./composables/useNotes')
  // @ts-ignore
  export type { FolderLayoutMode } from './composables/useSettings'
  import('./composables/useSettings')
  // @ts-ignore
  export type { TodoItem } from './composables/useTodos'
  import('./composables/useTodos')
  // @ts-ignore
  export type { ChromeBookmarkNode } from './utils/bookmarksApi'
  import('./utils/bookmarksApi')
  // @ts-ignore
  export type { ImageProcessResult, CompressionOptions } from './utils/imageProcessor'
  import('./utils/imageProcessor')
  // @ts-ignore
  export type { BaseDirection, Alignment, Rect, Viewport, PositionResult } from './utils/positioning'
  import('./utils/positioning')
  // @ts-ignore
  export type { WordCountResult } from './utils/wordCount'
  import('./utils/wordCount')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly COMMON_DICT: UnwrapRef<typeof import('./utils/pinyinDict')['COMMON_DICT']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly VIP_MAP: UnwrapRef<typeof import('./utils/pinyinDict')['VIP_MAP']>
    readonly buildFolderMap: UnwrapRef<typeof import('./utils/bookmarksApi')['buildFolderMap']>
    readonly calculateCoords: UnwrapRef<typeof import('./utils/positioning')['calculateCoords']>
    readonly checkFit: UnwrapRef<typeof import('./utils/positioning')['checkFit']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly debounce: UnwrapRef<typeof import('./utils/debounce')['debounce']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly deleteImage: UnwrapRef<typeof import('./utils/db')['deleteImage']>
    readonly downloadFile: UnwrapRef<typeof import('./utils/export')['downloadFile']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly extractFolders: UnwrapRef<typeof import('./utils/bookmarksApi')['extractFolders']>
    readonly flattenBookmarks: UnwrapRef<typeof import('./utils/bookmarksApi')['flattenBookmarks']>
    readonly getAllImageIds: UnwrapRef<typeof import('./utils/db')['getAllImageIds']>
    readonly getAllKeys: UnwrapRef<typeof import('./utils/db')['getAllKeys']>
    readonly getAvailableSpace: UnwrapRef<typeof import('./utils/positioning')['getAvailableSpace']>
    readonly getBookmarkTree: UnwrapRef<typeof import('./utils/bookmarksApi')['getBookmarkTree']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getFirstLetter: UnwrapRef<typeof import('./utils/pinyin')['getFirstLetter']>
    readonly getFolderPathFromMap: UnwrapRef<typeof import('./utils/bookmarksApi')['getFolderPathFromMap']>
    readonly getImageKeys: UnwrapRef<typeof import('./utils/db')['getImageKeys']>
    readonly getImageUrl: UnwrapRef<typeof import('./utils/db')['getImageUrl']>
    readonly getPinyinFirstLetters: UnwrapRef<typeof import('./utils/pinyin')['getPinyinFirstLetters']>
    readonly getWordCount: UnwrapRef<typeof import('./utils/wordCount')['getWordCount']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isExtensionEnvironment: UnwrapRef<typeof import('./utils/bookmarksApi')['isExtensionEnvironment']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly processImageWithWorker: UnwrapRef<typeof import('./utils/imageProcessor')['processImageWithWorker']>
    readonly processMarkdownForExport: UnwrapRef<typeof import('./utils/export')['processMarkdownForExport']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly provideContextMenu: UnwrapRef<typeof import('./composables/useContextMenu')['provideContextMenu']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly removeImage: UnwrapRef<typeof import('./utils/db')['removeImage']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly saveImage: UnwrapRef<typeof import('./utils/db')['saveImage']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly stripMarkdown: UnwrapRef<typeof import('./utils/export')['stripMarkdown']>
    readonly throttle: UnwrapRef<typeof import('./utils/throttle')['throttle']>
    readonly throttleRaf: UnwrapRef<typeof import('./utils/throttle')['throttleRaf']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAsyncWordCount: UnwrapRef<typeof import('./composables/useAsyncWordCount')['useAsyncWordCount']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCalendarData: UnwrapRef<typeof import('./composables/useCalendarData')['useCalendarData']>
    readonly useContextMenu: UnwrapRef<typeof import('./composables/useContextMenu')['useContextMenu']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDraggableCard: UnwrapRef<typeof import('./composables/useDraggableCard')['useDraggableCard']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useImageGC: UnwrapRef<typeof import('./composables/useImageGC')['useImageGC']>
    readonly useImageUpload: UnwrapRef<typeof import('./composables/useImageUpload')['useImageUpload']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNotes: UnwrapRef<typeof import('./composables/useNotes')['useNotes']>
    readonly useSettings: UnwrapRef<typeof import('./composables/useSettings')['useSettings']>
    readonly useShortcutDrag: UnwrapRef<typeof import('./composables/useShortcutDrag')['useShortcutDrag']>
    readonly useSimpleDrag: UnwrapRef<typeof import('./composables/useSimpleDrag')['useSimpleDrag']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTodoDrag: UnwrapRef<typeof import('./composables/useTodoDrag')['useTodoDrag']>
    readonly useTodos: UnwrapRef<typeof import('./composables/useTodos')['useTodos']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}