/**
 * Vite 插件：自动从 TypeScript 接口 JSDoc 注释生成字段标签映射
 *
 * 功能：
 * 1. 解析 src/types/index.ts 中的 Settings 和 IconConfig 接口
 * 2. 提取每个字段的 JSDoc 注释作为中文标签
 * 3. 生成虚拟模块 virtual:settings-labels 供运行时使用
 */

import { Plugin } from 'vite'
import * as fs from 'fs'
import * as path from 'path'

interface LabelMap {
  settings: Record<string, string>
  icon: Record<string, string>
}

/**
 * 解析 TypeScript 接口，提取字段名和 JSDoc 注释
 */
function parseInterfaceLabels(content: string, interfaceName: string): Record<string, string> {
  const labels: Record<string, string> = {}

  // 匹配接口定义块
  const interfaceRegex = new RegExp(
    `export\\s+interface\\s+${interfaceName}\\s*\\{([\\s\\S]*?)^\\}`,
    'm'
  )
  const match = content.match(interfaceRegex)

  if (!match) {
    console.warn(`[settings-labels] Interface ${interfaceName} not found`)
    return labels
  }

  const interfaceBody = match[1]

  // 匹配 JSDoc 注释和字段名
  // 格式: /** 中文标签 */\n  fieldName: type
  const fieldRegex = /\/\*\*\s*(.+?)\s*\*\/\s*\n\s*(\w+):/g
  let fieldMatch

  while ((fieldMatch = fieldRegex.exec(interfaceBody)) !== null) {
    const label = fieldMatch[1].trim()
    const fieldName = fieldMatch[2]
    labels[fieldName] = label
  }

  return labels
}

/**
 * 生成虚拟模块代码
 */
function generateModuleCode(labels: LabelMap): string {
  return `// Auto-generated by vite-plugin-settings-labels
// Do not edit manually

export const SETTINGS_LABELS = ${JSON.stringify(labels.settings, null, 2)}

export const ICON_LABELS = ${JSON.stringify(labels.icon, null, 2)}

export function getSettingLabel(key) {
  return SETTINGS_LABELS[key] || key
}

export function getIconLabel(key) {
  return ICON_LABELS[key] || key
}
`
}

export default function settingsLabelsPlugin(): Plugin {
  const virtualModuleId = 'virtual:settings-labels'
  const resolvedVirtualModuleId = '\0' + virtualModuleId

  let labels: LabelMap = { settings: {}, icon: {} }
  let typesFilePath = ''

  return {
    name: 'vite-plugin-settings-labels',

    configResolved(config) {
      typesFilePath = path.resolve(config.root, 'src/types/index.ts')
    },

    buildStart() {
      // 解析类型文件
      if (fs.existsSync(typesFilePath)) {
        const content = fs.readFileSync(typesFilePath, 'utf-8')
        labels = {
          settings: parseInterfaceLabels(content, 'Settings'),
          icon: parseInterfaceLabels(content, 'IconConfig')
        }
        console.log(`[settings-labels] Parsed ${Object.keys(labels.settings).length} settings, ${Object.keys(labels.icon).length} icon labels`)
      }
    },

    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId
      }
    },

    load(id) {
      if (id === resolvedVirtualModuleId) {
        return generateModuleCode(labels)
      }
    },

    handleHotUpdate({ file, server }) {
      // 类型文件变化时重新解析并触发 HMR
      if (file === typesFilePath) {
        const content = fs.readFileSync(typesFilePath, 'utf-8')
        labels = {
          settings: parseInterfaceLabels(content, 'Settings'),
          icon: parseInterfaceLabels(content, 'IconConfig')
        }
        console.log(`[settings-labels] Hot reloaded labels`)

        // 触发虚拟模块更新
        const mod = server.moduleGraph.getModuleById(resolvedVirtualModuleId)
        if (mod) {
          server.moduleGraph.invalidateModule(mod)
          return [mod]
        }
      }
    }
  }
}
