/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const CATEGORY_LABELS: typeof import('./utils/settings-meta').CATEGORY_LABELS
  const COMMON_DICT: typeof import('./utils/pinyinDict').COMMON_DICT
  const CURRENT_BACKUP_VERSION: typeof import('./utils/backup-validator').CURRENT_BACKUP_VERSION
  const DESKTOP_PRESETS: typeof import('./composables/useSettings').DESKTOP_PRESETS
  const ERROR_DECRYPTION_FAILED: typeof import('./utils/crypto').ERROR_DECRYPTION_FAILED
  const ERROR_INVALID_PASSWORD: typeof import('./utils/crypto').ERROR_INVALID_PASSWORD
  const EffectScope: typeof import('vue').EffectScope
  const ICON_CONFIG_META: typeof import('./utils/settings-meta').ICON_CONFIG_META
  const ICON_LABELS: typeof import('./utils/qr-codec').ICON_LABELS
  const IV_LENGTH: typeof import('./utils/crypto').IV_LENGTH
  const KEY_LENGTH: typeof import('./utils/crypto').KEY_LENGTH
  const MAX_QR_CHARS: typeof import('./utils/qr-codec').MAX_QR_CHARS
  const PBKDF2_ITERATIONS: typeof import('./utils/crypto').PBKDF2_ITERATIONS
  const PROTOCOL_VERSION: typeof import('./utils/qr-codec').PROTOCOL_VERSION
  const SALT_LENGTH: typeof import('./utils/crypto').SALT_LENGTH
  const SETTINGS_LABELS: typeof import('./utils/qr-codec').SETTINGS_LABELS
  const SETTINGS_META: typeof import('./utils/settings-meta').SETTINGS_META
  const SETTINGS_MIGRATION_MAP: typeof import('./composables/useSettings').SETTINGS_MIGRATION_MAP
  const VIP_MAP: typeof import('./utils/pinyinDict').VIP_MAP
  const analyzeBackup: typeof import('./utils/backup-diff').analyzeBackup
  const buildFolderMap: typeof import('./utils/bookmarksApi').buildFolderMap
  const calculateCoords: typeof import('./utils/positioning').calculateCoords
  const checkFit: typeof import('./utils/positioning').checkFit
  const cleanupOldSnapshots: typeof import('./utils/snapshot-storage').cleanupOldSnapshots
  const compressData: typeof import('./utils/crypto').compressData
  const computed: typeof import('vue').computed
  const converterCategories: typeof import('./composables/useConverter').converterCategories
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const debounce: typeof import('./utils/debounce').debounce
  const decode: typeof import('./utils/qr-codec').decode
  const decompressData: typeof import('./utils/crypto').decompressData
  const decrypt: typeof import('./utils/crypto').decrypt
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const deleteImage: typeof import('./utils/db').deleteImage
  const deleteSnapshot: typeof import('./utils/snapshot-storage').deleteSnapshot
  const downloadFile: typeof import('./utils/file').downloadFile
  const effectScope: typeof import('vue').effectScope
  const encode: typeof import('./utils/qr-codec').encode
  const encrypt: typeof import('./utils/crypto').encrypt
  const extractFolders: typeof import('./utils/bookmarksApi').extractFolders
  const flattenBookmarks: typeof import('./utils/bookmarksApi').flattenBookmarks
  const formatSettingValue: typeof import('./utils/settings-meta').formatSettingValue
  const generateIV: typeof import('./utils/crypto').generateIV
  const generateSalt: typeof import('./utils/crypto').generateSalt
  const getAllImageIds: typeof import('./utils/db').getAllImageIds
  const getAllKeys: typeof import('./utils/db').getAllKeys
  const getAllSnapshotMetas: typeof import('./utils/snapshot-storage').getAllSnapshotMetas
  const getAvailableSpace: typeof import('./utils/positioning').getAvailableSpace
  const getBookmarkTree: typeof import('./utils/bookmarksApi').getBookmarkTree
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getDetailedSettingsDiff: typeof import('./utils/backup-diff').getDetailedSettingsDiff
  const getFirstLetter: typeof import('./utils/pinyin').getFirstLetter
  const getFolderPathFromMap: typeof import('./utils/bookmarksApi').getFolderPathFromMap
  const getImageBlob: typeof import('./utils/db').getImageBlob
  const getImageKeys: typeof import('./utils/db').getImageKeys
  const getImageUrl: typeof import('./utils/db').getImageUrl
  const getPinyinFirstLetters: typeof import('./utils/pinyin').getPinyinFirstLetters
  const getSettingCategory: typeof import('./utils/settings-meta').getSettingCategory
  const getSettingLabel: typeof import('./utils/settings-meta').getSettingLabel
  const getSnapshot: typeof import('./utils/snapshot-storage').getSnapshot
  const getSnapshotCount: typeof import('./utils/snapshot-storage').getSnapshotCount
  const getWordCount: typeof import('./utils/wordCount').getWordCount
  const groupSettingsByCategory: typeof import('./utils/settings-meta').groupSettingsByCategory
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isExtensionEnvironment: typeof import('./utils/bookmarksApi').isExtensionEnvironment
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const packEncryptedData: typeof import('./utils/crypto').packEncryptedData
  const processImageWithWorker: typeof import('./utils/imageProcessor').processImageWithWorker
  const processMarkdownForExport: typeof import('./utils/export').processMarkdownForExport
  const provide: typeof import('vue').provide
  const provideContextMenu: typeof import('./composables/useContextMenu').provideContextMenu
  const reactive: typeof import('vue').reactive
  const readJsonFile: typeof import('./utils/file').readJsonFile
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const removeImage: typeof import('./utils/db').removeImage
  const resolveComponent: typeof import('vue').resolveComponent
  const saveImage: typeof import('./utils/db').saveImage
  const saveSnapshot: typeof import('./utils/snapshot-storage').saveSnapshot
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const stripMarkdown: typeof import('./utils/export').stripMarkdown
  const throttle: typeof import('./utils/throttle').throttle
  const throttleRaf: typeof import('./utils/throttle').throttleRaf
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toggleSnapshotLock: typeof import('./utils/snapshot-storage').toggleSnapshotLock
  const triggerRef: typeof import('vue').triggerRef
  const unpackEncryptedData: typeof import('./utils/crypto').unpackEncryptedData
  const unref: typeof import('vue').unref
  const useAsyncWordCount: typeof import('./composables/useAsyncWordCount').useAsyncWordCount
  const useAttrs: typeof import('vue').useAttrs
  const useCalculator: typeof import('./composables/useCalculator').useCalculator
  const useCalendarData: typeof import('./composables/useCalendarData').useCalendarData
  const useContextMenu: typeof import('./composables/useContextMenu').useContextMenu
  const useConverter: typeof import('./composables/useConverter').useConverter
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDailyPoem: typeof import('./composables/useDailyPoem').useDailyPoem
  const useDataBackup: typeof import('./composables/useDataBackup').useDataBackup
  const useDraggableCard: typeof import('./composables/useDraggableCard').useDraggableCard
  const useHistory: typeof import('./composables/useHistory').useHistory
  const useId: typeof import('vue').useId
  const useImageGC: typeof import('./composables/useImageGC').useImageGC
  const useImageUpload: typeof import('./composables/useImageUpload').useImageUpload
  const useModel: typeof import('vue').useModel
  const useNotes: typeof import('./composables/useNotes').useNotes
  const usePresets: typeof import('./composables/usePresets').usePresets
  const useSettings: typeof import('./composables/useSettings').useSettings
  const useShortcutDrag: typeof import('./composables/useShortcutDrag').useShortcutDrag
  const useSimpleDrag: typeof import('./composables/useSimpleDrag').useSimpleDrag
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTheme: typeof import('./composables/useTheme').useTheme
  const useTodoDrag: typeof import('./composables/useTodoDrag').useTodoDrag
  const useTodos: typeof import('./composables/useTodos').useTodos
  const validateBackup: typeof import('./utils/backup-validator').validateBackup
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { HistoryItem } from './composables/useCalculator'
  import('./composables/useCalculator')
  // @ts-ignore
  export type { DayMetadata } from './composables/useCalendarData'
  import('./composables/useCalendarData')
  // @ts-ignore
  export type { OptionItem } from './composables/useContextMenu'
  import('./composables/useContextMenu')
  // @ts-ignore
  export type { ConverterType, ConverterCategory } from './composables/useConverter'
  import('./composables/useConverter')
  // @ts-ignore
  export type { RestoreStats } from './composables/useDataBackup'
  import('./composables/useDataBackup')
  // @ts-ignore
  export type { Note, SortMode } from './composables/useNotes'
  import('./composables/useNotes')
  // @ts-ignore
  export type { TodoItem } from './composables/useTodos'
  import('./composables/useTodos')
  // @ts-ignore
  export type { SettingsDiffItem, DiffResult } from './utils/backup-diff'
  import('./utils/backup-diff')
  // @ts-ignore
  export type { BackupMeta, BackupContainer, ValidationResult } from './utils/backup-validator'
  import('./utils/backup-validator')
  // @ts-ignore
  export type { ChromeBookmarkNode } from './utils/bookmarksApi'
  import('./utils/bookmarksApi')
  // @ts-ignore
  export type { EncryptedData } from './utils/crypto'
  import('./utils/crypto')
  // @ts-ignore
  export type { ImageProcessResult, CompressionOptions } from './utils/imageProcessor'
  import('./utils/imageProcessor')
  // @ts-ignore
  export type { BaseDirection, Alignment, Rect, Viewport, PositionResult } from './utils/positioning'
  import('./utils/positioning')
  // @ts-ignore
  export type { SettingCategory, SettingMetaItem } from './utils/settings-meta'
  import('./utils/settings-meta')
  // @ts-ignore
  export type { WordCountResult } from './utils/wordCount'
  import('./utils/wordCount')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly CATEGORY_LABELS: UnwrapRef<typeof import('./utils/settings-meta')['CATEGORY_LABELS']>
    readonly COMMON_DICT: UnwrapRef<typeof import('./utils/pinyinDict')['COMMON_DICT']>
    readonly CURRENT_BACKUP_VERSION: UnwrapRef<typeof import('./utils/backup-validator')['CURRENT_BACKUP_VERSION']>
    readonly DESKTOP_PRESETS: UnwrapRef<typeof import('./composables/useSettings')['DESKTOP_PRESETS']>
    readonly ERROR_DECRYPTION_FAILED: UnwrapRef<typeof import('./utils/crypto')['ERROR_DECRYPTION_FAILED']>
    readonly ERROR_INVALID_PASSWORD: UnwrapRef<typeof import('./utils/crypto')['ERROR_INVALID_PASSWORD']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly ICON_CONFIG_META: UnwrapRef<typeof import('./utils/settings-meta')['ICON_CONFIG_META']>
    readonly IV_LENGTH: UnwrapRef<typeof import('./utils/crypto')['IV_LENGTH']>
    readonly KEY_LENGTH: UnwrapRef<typeof import('./utils/crypto')['KEY_LENGTH']>
    readonly PBKDF2_ITERATIONS: UnwrapRef<typeof import('./utils/crypto')['PBKDF2_ITERATIONS']>
    readonly SALT_LENGTH: UnwrapRef<typeof import('./utils/crypto')['SALT_LENGTH']>
    readonly SETTINGS_META: UnwrapRef<typeof import('./utils/settings-meta')['SETTINGS_META']>
    readonly SETTINGS_MIGRATION_MAP: UnwrapRef<typeof import('./composables/useSettings')['SETTINGS_MIGRATION_MAP']>
    readonly VIP_MAP: UnwrapRef<typeof import('./utils/pinyinDict')['VIP_MAP']>
    readonly analyzeBackup: UnwrapRef<typeof import('./utils/backup-diff')['analyzeBackup']>
    readonly buildFolderMap: UnwrapRef<typeof import('./utils/bookmarksApi')['buildFolderMap']>
    readonly calculateCoords: UnwrapRef<typeof import('./utils/positioning')['calculateCoords']>
    readonly checkFit: UnwrapRef<typeof import('./utils/positioning')['checkFit']>
    readonly cleanupOldSnapshots: UnwrapRef<typeof import('./utils/snapshot-storage')['cleanupOldSnapshots']>
    readonly compressData: UnwrapRef<typeof import('./utils/crypto')['compressData']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly converterCategories: UnwrapRef<typeof import('./composables/useConverter')['converterCategories']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly debounce: UnwrapRef<typeof import('./utils/debounce')['debounce']>
    readonly decompressData: UnwrapRef<typeof import('./utils/crypto')['decompressData']>
    readonly decrypt: UnwrapRef<typeof import('./utils/crypto')['decrypt']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly deleteImage: UnwrapRef<typeof import('./utils/db')['deleteImage']>
    readonly deleteSnapshot: UnwrapRef<typeof import('./utils/snapshot-storage')['deleteSnapshot']>
    readonly downloadFile: UnwrapRef<typeof import('./utils/file')['downloadFile']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly encrypt: UnwrapRef<typeof import('./utils/crypto')['encrypt']>
    readonly extractFolders: UnwrapRef<typeof import('./utils/bookmarksApi')['extractFolders']>
    readonly flattenBookmarks: UnwrapRef<typeof import('./utils/bookmarksApi')['flattenBookmarks']>
    readonly formatSettingValue: UnwrapRef<typeof import('./utils/settings-meta')['formatSettingValue']>
    readonly generateIV: UnwrapRef<typeof import('./utils/crypto')['generateIV']>
    readonly generateSalt: UnwrapRef<typeof import('./utils/crypto')['generateSalt']>
    readonly getAllImageIds: UnwrapRef<typeof import('./utils/db')['getAllImageIds']>
    readonly getAllKeys: UnwrapRef<typeof import('./utils/db')['getAllKeys']>
    readonly getAllSnapshotMetas: UnwrapRef<typeof import('./utils/snapshot-storage')['getAllSnapshotMetas']>
    readonly getAvailableSpace: UnwrapRef<typeof import('./utils/positioning')['getAvailableSpace']>
    readonly getBookmarkTree: UnwrapRef<typeof import('./utils/bookmarksApi')['getBookmarkTree']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getDetailedSettingsDiff: UnwrapRef<typeof import('./utils/backup-diff')['getDetailedSettingsDiff']>
    readonly getFirstLetter: UnwrapRef<typeof import('./utils/pinyin')['getFirstLetter']>
    readonly getFolderPathFromMap: UnwrapRef<typeof import('./utils/bookmarksApi')['getFolderPathFromMap']>
    readonly getImageBlob: UnwrapRef<typeof import('./utils/db')['getImageBlob']>
    readonly getImageKeys: UnwrapRef<typeof import('./utils/db')['getImageKeys']>
    readonly getImageUrl: UnwrapRef<typeof import('./utils/db')['getImageUrl']>
    readonly getPinyinFirstLetters: UnwrapRef<typeof import('./utils/pinyin')['getPinyinFirstLetters']>
    readonly getSettingCategory: UnwrapRef<typeof import('./utils/settings-meta')['getSettingCategory']>
    readonly getSettingLabel: UnwrapRef<typeof import('./utils/settings-meta')['getSettingLabel']>
    readonly getSnapshot: UnwrapRef<typeof import('./utils/snapshot-storage')['getSnapshot']>
    readonly getSnapshotCount: UnwrapRef<typeof import('./utils/snapshot-storage')['getSnapshotCount']>
    readonly getWordCount: UnwrapRef<typeof import('./utils/wordCount')['getWordCount']>
    readonly groupSettingsByCategory: UnwrapRef<typeof import('./utils/settings-meta')['groupSettingsByCategory']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isExtensionEnvironment: UnwrapRef<typeof import('./utils/bookmarksApi')['isExtensionEnvironment']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly packEncryptedData: UnwrapRef<typeof import('./utils/crypto')['packEncryptedData']>
    readonly processImageWithWorker: UnwrapRef<typeof import('./utils/imageProcessor')['processImageWithWorker']>
    readonly processMarkdownForExport: UnwrapRef<typeof import('./utils/export')['processMarkdownForExport']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly provideContextMenu: UnwrapRef<typeof import('./composables/useContextMenu')['provideContextMenu']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readJsonFile: UnwrapRef<typeof import('./utils/file')['readJsonFile']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly removeImage: UnwrapRef<typeof import('./utils/db')['removeImage']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly saveImage: UnwrapRef<typeof import('./utils/db')['saveImage']>
    readonly saveSnapshot: UnwrapRef<typeof import('./utils/snapshot-storage')['saveSnapshot']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly stripMarkdown: UnwrapRef<typeof import('./utils/export')['stripMarkdown']>
    readonly throttle: UnwrapRef<typeof import('./utils/throttle')['throttle']>
    readonly throttleRaf: UnwrapRef<typeof import('./utils/throttle')['throttleRaf']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly toggleSnapshotLock: UnwrapRef<typeof import('./utils/snapshot-storage')['toggleSnapshotLock']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unpackEncryptedData: UnwrapRef<typeof import('./utils/crypto')['unpackEncryptedData']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAsyncWordCount: UnwrapRef<typeof import('./composables/useAsyncWordCount')['useAsyncWordCount']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCalculator: UnwrapRef<typeof import('./composables/useCalculator')['useCalculator']>
    readonly useCalendarData: UnwrapRef<typeof import('./composables/useCalendarData')['useCalendarData']>
    readonly useContextMenu: UnwrapRef<typeof import('./composables/useContextMenu')['useContextMenu']>
    readonly useConverter: UnwrapRef<typeof import('./composables/useConverter')['useConverter']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDataBackup: UnwrapRef<typeof import('./composables/useDataBackup')['useDataBackup']>
    readonly useDraggableCard: UnwrapRef<typeof import('./composables/useDraggableCard')['useDraggableCard']>
    readonly useHistory: UnwrapRef<typeof import('./composables/useHistory')['useHistory']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useImageGC: UnwrapRef<typeof import('./composables/useImageGC')['useImageGC']>
    readonly useImageUpload: UnwrapRef<typeof import('./composables/useImageUpload')['useImageUpload']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNotes: UnwrapRef<typeof import('./composables/useNotes')['useNotes']>
    readonly usePresets: UnwrapRef<typeof import('./composables/usePresets')['usePresets']>
    readonly useSettings: UnwrapRef<typeof import('./composables/useSettings')['useSettings']>
    readonly useSimpleDrag: UnwrapRef<typeof import('./composables/useSimpleDrag')['useSimpleDrag']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTheme: UnwrapRef<typeof import('./composables/useTheme')['useTheme']>
    readonly useTodoDrag: UnwrapRef<typeof import('./composables/useTodoDrag')['useTodoDrag']>
    readonly useTodos: UnwrapRef<typeof import('./composables/useTodos')['useTodos']>
    readonly validateBackup: UnwrapRef<typeof import('./utils/backup-validator')['validateBackup']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}